import { Inter } from "next/font/google";
import "./globals.css";
import AnimatedBackground from "@/components/AnimatedBackground"; // ← Add this

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sherwin Rodriguez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased relative`}>
        <AnimatedBackground />
        {children}
      </body>
    </html>
  );
}
